### ISSUE TITLE
[Domain Publisher] Shows status 'imported' while it should show transaction id instead. Imported is wrong.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#109]
![image](https://user-images.githubusercontent.com/45313235/137280397-071a6ccb-02f7-41cb-a6c4-23feb165b51a.png)

**Comment by FantasticoFox** [comment]
Solution proposal: we check the domain manifest name with domain id and only count up if it's within our own domain.

**Comment by FantasticoFox** [comment]
@rht is the functionality implemented that if a page gets imported, but no domain manifest exists for it it shows N/A and if it gets later imported it's matched to the correct witness_event_id in the DB and links it correct into the domain_manifest_publisher for visiblity?

**Comment by rht** [comment]
No, unlikely to have been implemented I think.

**Comment by FantasticoFox** [comment]
linked to #139

**Comment by FantasticoFox** [comment]
Missing peace is recovery of domain-id after backup and restore.

**Comment by FantasticoFox** [comment]
#158

**Comment by 0xc0000007b** [comment]
Fixed with backup work.

**Comment by FantasticoFox** [comment]
And with reworking how we store our config.
