### ISSUE TITLE
Navigating back (browser back button) to the Domain Manifest Generator screen requires a form resubmission

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#113]
Potential work around could be opening a new tab for links in the domain manifest generator screen?

Steps to re create:
-go to localhost for PKC
-go through login process
-Click on "Domain Manifest Generator"
-Click "Generate Domain Manifest"
-Click on "Main Page" under Page Title column heading
-The Main Page is displayed, but when you hit the "Back" browser button, you get the form resubmission page

**Comment by FantasticoFox** [comment]
It's standard browser behavior for going back after form submission.
