### ISSUE TITLE
CI: Decide whether to use MediaWiki's api-testing vs MediaWikiIntegrationTestCase for API testing

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#121]
Currently we use api-testing, but setting up apache2 server with php support is slow (could be made faster with a pre-built Docker image).
Here is an example of using the latter: https://github.com/ProfessionalWiki/GND/blob/master/tests/Integration/DokuApiTest.php.

**Comment by JeroenDeDauw** [comment]
What is the former? This? https://www.mediawiki.org/wiki/API:Calling_internally

Note that recent versions of MediaWiki have two distinct API systems: the "action API" and the REST API. Each comes with their own testing utilities. 

The GND extension uses the REST API. The test there was designed to minimize binding to the framework (MediaWiki) and to minimize inheritance abuse.

**Comment by rht** [comment]
The former is https://www.npmjs.com/package/api-testing. From the description, it seems to be tailor-made for MediaWiki tests.
This repo uses the REST API.

**Comment by rht** [comment]
Copy pasted @JeroenDeDauw 's answer from Matrix chat:
```
> isn't it expected for integration tests to capture extra problems such as the mediawiki issues?
Earlier I was thinking that since the PHP tests use a MediaWiki wrapper, they do not test making a plain request to the API. So if you misunderstand the wrapper you might implement the wrong API, and still have the tests pass. In practice you would find out immediately when using the API, and regressions here seem unlikely. Now I've seen that the JS tests also use a wrapper, so you do get extremely little practical benefit as far as I can tell. Not worth the extra complexity, even if you did not need a prebuild Docker image to make the CI run in reasonable time.
```

We will switch to `MediaWikiIntegrationTestCase`.
