### ISSUE TITLE
[PERF] Optimize DB call in VerifiedWikiImporter.php

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#135]
https://github.com/inblockio/DataAccounting/blob/52265015ef60a2f098a1030d051fe536cef1750e/includes/VerifiedWikiImporter.php#L1109-L1119

We should do `selectRow` and `[ 'ORDER BY' => 'page_verification_id DESC' ]`

**Comment by FantasticoFox** [comment]
We switched to new importer.
