### ISSUE TITLE
[Backup / Restore] Include Localsettings.php in .pkc backup / .pkc restore

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#139]
currently we do not include the Localsettings.php

**Comment by FantasticoFox** [comment]
Solution proposal: Break and restore symlink before and after backup

**Comment by FantasticoFox** [comment]
related to #109

**Comment by FantasticoFox** [comment]
Obsolete as it will be included in the DB after the redesign of the config handling.

**Comment by it-spiderman** [comment]
LocalSettings.php is considered local and private file, and in most cases its not ment to be included in backups.
Yes, it will be automatically generated when MW installer runs.

Unless something changes recently, i tought DB config would only store `DA`-specific configs. If you want to configure other parts of MW, this would still need to be done in LocalSettings.

One way to improve this is to modify the installer, to include another file, eg. `LocalSettings.PKC.php` in the LocalSettings.php when generating it. Then you would be free to add any number of configs in here, which would be backup-safe and could be tracked in git.

**Comment by FantasticoFox** [comment]
> One way to improve this is to modify the installer, to include another file, eg. `LocalSettings.PKC.php` in the LocalSettings.php when generating it. Then you would be free to add any number of configs in here, which would be backup-safe and could be tracked in git.

This is how we do it currently. We keep it this way. So this is a won't fix. We handle all other related settings via the config.
