### ISSUE TITLE
Full history by default on our export page

### ISSUE THREAD

**Issue by JeroenDeDauw** [inblockio/DataAccounting#146]
We want the `Include only the current revision, not the full history` checkbox on Special:Export to not be checked by default, as was the case on Special:VerifiedExport (removed in https://github.com/inblockio/DataAccounting/pull/144)

**Comment by JeroenDeDauw** [comment]
Currently I see these options:

* Run some JavaSscript. Downside: default only changes for people with JS enabled and only after the page finished loading.
* Copy most of Special:Export again and have a second export page like we did before with Special:VerifiedExport
* Do not change the default
* Modify MediaWiki: add hook. Complications: need to get the change in MW itself and we'll raise the minimum version of future MW 38

It might also be possible to modify the HTML via an existing hook, I will investigate this.

**Comment by FantasticoFox** [comment]
This seems most practical to keep control of behaviour; having a hook in MW38 would help but...

We will need to modify / extent the 'include' templates functionality in the future. This will add another reason to use a dedicated special page again.

So I propose we go back to: Copy most of Special:Export again and have a second export page like we did before with Special:VerifiedExport

**Comment by JeroenDeDauw** [comment]
If we have the hooks needed to modify the form and how submission is handled, then it does not matter much if we change the default of one checkbox, or add a bunch of fields.

What would the ideal export page for your use case look like? I'm guessing it would not have the "full history" option at all. What about the other options? And what about the text? If we create a new page anyway, we can strip out everything that is not needed, improving both UX and maintainability. And which things are you thinking off adding, like this extended templates thing, which I currently do not understand?

**Comment by FantasticoFox** [comment]
Ideal:

- No option for history (on by default)
- have the field to add the page title first (not after category, everyone posts their page the first time in the category field and it doesn't work)

- the add field page text would support autocomplete / search to eliminate the need to copy page titles and go back and forth 

For future development
- have an option to selects 'include linked sub-pages until a depth of 'X'
- include templates should be auto activated / be true
- have an option to include transcluded pages on/off (right now it's default on)

**Comment by FantasticoFox** [comment]
Text: Verified Export includes verification data of the MW 'Data Accounting' extension. 

This pages offers additional export options to improve the ability to port verifiable data between wikis with the 'Data Accounting' Extension.

**Comment by JeroenDeDauw** [comment]
Ok, will look into dedicated page with minimal code duplication.

To keep a copy for myself, here is the experiments to modify Special:Export itself that I did:

```php
//$wgHooks['AfterFinalPageOutput'][] = function( $output ) {
//	$out = ob_get_clean();
//	// change final html in $out
//	ob_start();
//	echo str_replace("checked='checked'", '', $out);
//};

$wgHooks['SpecialPageBeforeExecute'][] = function( SpecialPage $special, ?string $subPage ) {
	if ( $special instanceof SpecialExport ) {
//		$GLOBALS['wgExportAllowHistory'] = false;
//
//		$reflect = new ReflectionClass(SpecialExport::class);
//		$reflect->getMethod('doExport')->getParameters()[4]->set

//		$special->getRequest()->setVal( 'exportall', $special->getRequest()->getRawVal( 'exportall' ) ?? true );
	}

};

$wgHooks['SpecialPageAfterExecute'][] = function( SpecialPage $special, ?string $subPage ) {
	if ( $special instanceof SpecialExport ) {

	}
};
```

**Comment by JeroenDeDauw** [comment]
Special:Export has an option to export all pages. It is only shown when `wgExportAllowAll` is set to `true` in LocalSettings.php.

![image](https://user-images.githubusercontent.com/146040/141810209-00eb928c-a567-4301-a4bd-e9bccd255f69.png)

Perhaps it is useful to always have it in our own export page? I'm not sure what the typical use case for exporting is. One page? Several pages? All pages?

**Comment by JeroenDeDauw** [comment]
There is also an option to add pages from a namespace, again hidden behind some config that defaults to false.

![image](https://user-images.githubusercontent.com/146040/141811956-7bcf08eb-f505-4f54-89ad-7baaf838bf73.png)
