### ISSUE TITLE
Wrap persistance access (code quality)

### ISSUE THREAD

**Issue by JeroenDeDauw** [inblockio/DataAccounting#151]
The extension adds 3 DB tables. These tables are read from and written to in various places.

My recommendation is to put all code directly interacting with these tables in persistence services, for instance by using the Repository Pattern. This gives us

* separation of concerns (no mixing of persistence details with application and domain logic)
* increased modularity and composability, which also means more testability (can use alternative implementations of the persistence services, like test doubles)
* less chance for the need of Shotgun Surgery

**Comment by JeroenDeDauw** [comment]
Example of a refactor going in this direction: https://github.com/inblockio/DataAccounting/pull/153/commits/37d9e953db2643566e42d56501460fd9d89826f4 note that the service in that commit is not complete. There still is a bunch of code directly talking to the table outside the service, and the service will need at least one extra method (for writes), possibly more.

**Comment by FantasticoFox** [comment]
We wait for the abstraction to be required and come back to it.
