### ISSUE TITLE
Localsettings.php / symlink in backup is overriding Localsettings in the container

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#158]
This is problematic as you might deactivate public read, but the Localsettings in the backup-folder does not have the same setting continue allowing public access. This resulted in us publicly making internal project pages available. 

We need to review that this is not happening again.

This was also addressed by the --private deployment function.

**Comment by FantasticoFox** [comment]
Backup / Restore script breaks the symlink

**Comment by 0xc0000007b** [comment]
Some design work needed. Look at mountpoints

**Comment by FantasticoFox** [comment]
Removing it and adding it via a copy into the tarball seems a good way forward. Thanks for the chat @0xc0000007b

**Comment by FantasticoFox** [comment]
Will be not necessary as we put the config in the future in the DB. This issue will be closed with the new service handler for the config.

**Comment by rht** [comment]
Fixed in https://github.com/inblockio/MediaWiki_Backup/commit/0c161b9bd7f3b8963301032af12c41bb8fb3f013.

**Comment by FantasticoFox** [comment]
Added new related issue https://github.com/inblockio/micro-PKC/issues/97 for <domain_id><$wgservername>
