### ISSUE TITLE
MW 37 Depreciation warnings

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#159]
Jeroen said: Make sure the extensions, skins and "PHP packages in vendor/" are updated. If they are still the same as they where with MW 35 then getting errors is expected.

````
Populating /var/www/html/aqua/PKC-Content/Verified_Data.wiki into wiki
PHP Deprecated:  Premature access to service container [Called from EmbedVideoHooks::onExtension in /var/www/html/extensions/EmbedVideo/EmbedVideo.hooks.php at line 77] in /var/www/html/includes/debug/MWDebug.php on line 375
PHP Deprecated:  Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /var/www/html/includes/MediaWikiServices.php at line 267] in /var/www/html/includes/debug/MWDebug.php on line 375
PHP Deprecated:  Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /var/www/html/includes/ServiceWiring.php at line 618] in /var/www/html/includes/debug/MWDebug.php on line 375
PHP Deprecated:  Premature access to service 'ConfigFactory' [Called from EmbedVideoHooks::onExtension in /var/www/html/extensions/EmbedVideo/EmbedVideo.hooks.php at line 77] in /var/www/html/includes/debug/MWDebug.php on line 375
PHP Deprecated:  Premature access to service 'BootstrapConfig' [Called from Wikimedia\Services\ServiceContainer::{closure} in /var/www/html/includes/ServiceWiring.php at line 346] in /var/www/html/includes/debug/MWDebug.php on line 375
````

**Comment by FantasticoFox** [comment]
Closed by 801a55e70dd8e1b7acb38e61f69cca5c17b0746d

**Comment by FantasticoFox** [comment]
Actually it's not removed as expected

**Comment by FantasticoFox** [comment]
@0xc0000007b please rebuild docker image after commenting out https://github.com/inblockio/docker-aqua-mediawiki/blob/c80f0e9302d13992a1e6b9b904d5db05ab1bba9c/build.sh#L34 which causes deprecation warning

**Comment by 0xc0000007b** [comment]
> @0xc0000007b please rebuild docker image after commenting out https://github.com/inblockio/docker-aqua-mediawiki/blob/c80f0e9302d13992a1e6b9b904d5db05ab1bba9c/build.sh#L34 which causes deprecation warning

This change did not address the issue. I've opened a bug in the `micro-PKC` repo so we can close it with a pull reqeust.
https://github.com/inblockio/micro-PKC/issues/92.
