### ISSUE TITLE
Vanilla export and verified export fail on MW 37, PHP 8

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#160]
```
[exception] [6e308f8bc1cf204bfdd51b3c] /index.php/Special:Export   TypeError: Unsupported operand types: array & int
#0 /var/www/html/includes/export/WikiExporter.php(214): WikiExporter->dumpFrom(string)
#1 /var/www/html/includes/specials/SpecialExport.php(413): WikiExporter->pageByTitle(Title)
#2 /var/www/html/includes/specials/SpecialExport.php(200): SpecialExport->doExport(string, array, boolean, boolean)
#3 /var/www/html/includes/specialpage/SpecialPage.php(647): SpecialExport->execute(NULL)
#4 /var/www/html/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(NULL)
#5 /var/www/html/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#6 /var/www/html/includes/MediaWiki.php(925): MediaWiki->performRequest()
#7 /var/www/html/includes/MediaWiki.php(559): MediaWiki->main()
#8 /var/www/html/index.php(53): MediaWiki->run()
#9 /var/www/html/index.php(46): wfIndexMain()
#10 {main}
[DBConnection] Wikimedia\Rdbms\LoadBalancer::getLocalConnection: reused a connection for local/0
[DBQuery] Wikimedia\Rdbms\Database::beginIfImplied (LCStoreDB::get) [0s] database: BEGIN
[DBQuery] LCStoreDB::get [0.001s] database: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'en' AND lc_key = 'messages:internalerror'  LIMIT 1  
[DBQuery] MediaWiki::restInPeace [0.001s] database: COMMIT
[DBReplication] LBFactory shutdown completed
Request ended normally
[session] Saving all sessions on shutdown
[DBConnection] Wikimedia\Rdbms\LBFactory::destroy: closing connection to database 'database'.
```

**Comment by rht** [comment]
I traced the location of the error to https://github.com/wikimedia/mediawiki/blob/6e296116426e42aa57f8fa907158aa2552438cac/includes/export/WikiExporter.php#L311. The value of `$this->history` is `{"dir":"asc","offset":false,"limit":0}`, while the value of `self::LOGS` is 8. So it is a type mismatch. I suppose this is because PHP 8 is stricter with type coerciens? cc: @JeroenDeDauw

**Comment by rht** [comment]
I fixed it by changing the line in WikiExporter.php to apply `boolval()` to `$this->history`. Can I conclude that this is a MW bug and needs to be fixed upstream?

**Comment by JeroenDeDauw** [comment]
It might be a MW bug and it might be caught now with PHP 8. Though that would make it a bit surprising [the code is still unchanged on master](https://github.com/wikimedia/mediawiki/blob/master/includes/export/WikiExporter.php#L311), as I'd have expected such things to really be fixed by now.

Not clear to me that boolval is the right approach here. Note that the operand is `&`, not `&&`. That itself might be a mistake. Though since both sides can be int, perhaps not. Weird MediaWiki code with unclear original intent.

**Comment by rht** [comment]
It will take a while for the fix to arrive upstream. So for now, I will just apply a patch to WikiExporter.php during the PKC deployment.

**Comment by rht** [comment]
I tried `$this->history && self::LOGS` by itself, but it didn't work. The `boolval()` is still needed. There are multiple occurrences of `$this->history & self::<STUFF>` pattern, which leads me to conclude that it needs to be `&&`, not `&`.

**Comment by rht** [comment]
I tried `&&`, and it failed. Anyway, temporary fix in https://github.com/inblockio/micro-PKC/pull/80.

**Comment by FantasticoFox** [comment]
We reverted back to PHP 7.4 and treat this as a future compatibility issue

**Comment by mrglaser** [comment]
I suggest closing this issue for now. At the time MediaWiki is fully compatible with PHP8, upgrading the DataAccounting extension to PHP8 should be a separate task.

**Comment by rht** [comment]
Make sense.
