### ISSUE TITLE
Current build & tests fail under PHP8 

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#170]
New users are able to install the current version of our main with a working code-base.

**Comment by 0xc0000007b** [comment]
Please add business justification

**Comment by FantasticoFox** [comment]
Jeroen provided this https://github.com/ProfessionalWiki/mw-docker#mediawiki-docker-images

**Comment by FantasticoFox** [comment]
> Please add business justification

Post: No working code, unable to demo / pilot.

**Comment by FantasticoFox** [comment]
- [x] rebuild docker image and PHP 7.4
- [ ] Revise the syntax errors in Data/Accounting for PHP 7.4

**Comment by FantasticoFox** [comment]
Verified by running through our manual test protocol.

- run the setup
- login; this test metamask login with EAUTH
- create a test page / verify the test page
- sign the test page / verify the test page, check signature; this also confirms that the last verification hash is correctly entangled; this also tests the Metamask-Signing process
- generate domain manifest, publish domain manifest; this verifies that the publishing with Metamask works
- verify domain manifest, that it is renamed with the genesis hash, that it itself is witnessed
- verify test page; check that the witness data is included correctly
- export test page, delete test page in the wiki
- import test page and verify it, see if it checks out after the round trip; this verifies exporter and importer
- create a new revision of the test page
- export test page, delete test page
- import the first version of the test page with the shorter chain hight
- import the second version of the test page with the longer chain hight
- check if the shorter one was moved and renamed; and the longer one is the new test page; this verifies if the basic name-space collision is working.

**Comment by FantasticoFox** [comment]
https://pkc.inblock.io/index.php/PKC_Manuel_Test_Protocol
