### ISSUE TITLE
Logic-Error: Using wrong hash for Witness-Data (Using Witness_Event_Verification_Hash instead of Domain_Manifest_Verification_Hash)

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#171]
This will lead us to drop all verification data, as it breaks all pages.
We need to start clean by dropping tables for verification data.

**Comment by rht** [comment]
Fixed in:
- this repo: #173
- external verifier: https://github.com/inblockio/data-accounting-external-verifier/commit/11b02e0d536b203d301c6e47d2daa996b2bf3808
-VerifyPage: https://github.com/inblockio/VerifyPage/commit/d6c41532e82f82baf5b921195e066966dfecf602

**Comment by FantasticoFox** [comment]
Tested! :shipit:
