### ISSUE TITLE
User needs to complete a challenge when adding a link in this PKC 

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#179]
e.g. 46+1 = 47 this feature clearly comes from avoiding bots adding content into wiki-pages.
This is not required in PKC. What setting can we change to deactivate it?

**Comment by mrglaser** [comment]
This comes from the extension [ConfirmEdit](https://www.mediawiki.org/wiki/Extension:ConfirmEdit). As a default, there is a setting `$wgCaptchaTriggers['addurl'] = true;`. This needs to be set to `false`

**Comment by FantasticoFox** [comment]
Showing up rarely, unclear when it's triggered. Set it to low.

**Comment by FantasticoFox** [comment]
@rht please remove #wfLoadExtension( 'ConfirmEdit' ); for our build.
