### ISSUE TITLE
Users can install the extension from the Google-App-Store

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#184]
Users are able to install the Extension via the Google-App-Store.

**Comment by 0xc0000007b** [comment]
Last time I went the submission process it took about 1-2 hours to grok and ensure things were running smoothly. Unlike Apple there was no gating process and the extension was on the Chrome Web Store in a matter of minutes following the $5 submission fee. That was 5 years ago, so things may have changed a little. But overall the process is fairly straightforward.

**Comment by FantasticoFox** [comment]
VerifyPage Status: Pending reviewID; timeout is end of December.

**Comment by FantasticoFox** [comment]
![image](https://user-images.githubusercontent.com/45313235/144210864-1560dbfc-c887-44b3-97b7-0a1eeb9368dc.png)

Extension can now be installed via link (unlisted): https://chrome.google.com/webstore/detail/verifypage/gadnjgadnjidhhadchnegnpadkibmjlgihiajidhhadchnegnpadkibmjlgihiaj?hl=en-GB&authuser=0

**Comment by 0xc0000007b** [comment]
https://chrome.google.com/webstore/detail/verifypage/gadnjidhhadchnegnpadkibmjlgihiaj?hl=en-GB&authuser=0 listed extension link updated in PKC here: https://pkc.inblock.io/index.php/Setting_up_the_development_environment
