### ISSUE TITLE
get_server_info API endpoint is not yet tested

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#193]

**Comment by FantasticoFox** [comment]
can you please check with @pwirth if this is included now?

**Comment by pwirth** [comment]
it is already tested here:
https://github.com/inblockio/DataAccounting/blob/main/tests/phpunit/integration/DAApiTest.php#L41

**Comment by pwirth** [comment]
however there is still some rest api handlers, that are not tested at all, so i started implementing the tests here:
https://github.com/inblockio/DataAccounting/tree/apitests
