### ISSUE TITLE
[Template] Changing the content of a template file leads to no verification error 

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#211]
![image](https://user-images.githubusercontent.com/45313235/145209327-df008616-7eef-4285-a116-ac1a75f967a4.png)

I don't understand the behavior while the page checks out. Maybe it's a caching issue. But this is a quite severe Bug as we would not detect manipulations in pages which use 'templates',

**Comment by it-spiderman** [comment]
do you mean change in a template that is included on another page? so you change included template and the page that includes it still is verified, while the displayed content is changed?

**Comment by FantasticoFox** [comment]
> do you mean change in a template that is included on another page? so you change included template and the page that includes it still is verified, while the displayed content is changed?

Actually no. I did not change something in the template. As a template is a transcluded resource maybe we should also treated like that. What I changed was in the revision of the actual page content file, the content. 

But it seems that the content is cached and the API returns a cached state of the page. If I docker-compose down / up and do it again it will catch the error correctly with a content_hash mismatch.

**Comment by FantasticoFox** [comment]
Is this resolved by deactivating media-wiki legacy cache @it-spiderman ?

**Comment by FantasticoFox** [comment]
Added Cache deactivation based on https://www.mediawiki.org/wiki/Manual:FAQ#How_do_I_completely_disable_caching?

$wgEnableParserCache = false; // deprecated method
$wgParserCacheType = CACHE_NONE;
$wgCachePages = false;

This should resolve the issue, as the template is not longer cached.
