### ISSUE TITLE
[Tweeki] We only require a 'Login' button no 'Login / Create Account'

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#228]
![image](https://user-images.githubusercontent.com/45313235/147627590-accf4ed6-1bcc-42e8-914e-ffe13ff51159.png)

how do we change so it only shows Login?

**Comment by thaider** [comment]
The text can be changed by editing the page ```MediaWiki:Tweeki-login```.

**Comment by FantasticoFox** [comment]
Tested, worked. Thanks!
