### ISSUE TITLE
[Tweeki] Print view contains undesired elements (GUI Tweeki Buttons)

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#232]
[Interactive Tutorial - Personal Knowledge Container.pdf](https://github.com/inblockio/DataAccounting/files/7787349/Interactive.Tutorial.-.Personal.Knowledge.Container.pdf)

See attached the print-view of a current version of the PKC with Tweeki. It contains undesired elements like the GUI buttons.
How can we improve Tweeki to auto-hide those elements for the print?

**Comment by thaider** [comment]
should be fixed in the latest release (Tweeki 2.0.0)
