### ISSUE TITLE
CI does not catch unused variables

### ISSUE THREAD

**Issue by mrglaser** [inblockio/DataAccounting#236]
The current CI test does not catch unused variables. We need to amend the phpcs rules so they check for this.

**Comment by mrglaser** [comment]
- PHP CS is triggered here: https://github.com/inblockio/DataAccounting/blob/main/.github/workflows/ci.yml#L209
- PHP CS config: https://github.com/inblockio/DataAccounting/blob/main/.phpcs.xml
- Ruleset for unused variables: https://opensourcelibs.com/lib/phpcs-variable-analysis

**Comment by pwirth** [comment]
i added the package and rule to phpcs:
https://github.com/inblockio/DataAccounting/pull/224/commits/6b3432a857c39694e5c7f570306a9b85e3797e44

unfortunately we can not use the rule for unused variables as this would complain for unused variables within the method signature as well and we need to stay compatible on extending classes. so i excluded it.
VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable

The rest however workes fine!

**Comment by pwirth** [comment]
merged
