### ISSUE TITLE
WriteStoreWitnessTx: addReceiptToDomainManifest uses an old version of $witnessEvent

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#247]
The DB entry is updated in https://github.com/inblockio/DataAccounting/blob/cdc09b38e08785f2400db0e8bd7ce9b32fb73404/includes/API/WriteStoreWitnessTxHandler.php#L126, but the `$witnessEvent` is not updated. This not-yet-updated `$witnessEvent` is then used in https://github.com/inblockio/DataAccounting/blob/cdc09b38e08785f2400db0e8bd7ce9b32fb73404/includes/API/WriteStoreWitnessTxHandler.php#L145.

**Comment by it-spiderman** [comment]
see https://github.com/inblockio/DataAccounting/pull/249

**Comment by rht** [comment]
Fixed in #249.
