### ISSUE TITLE
[Tweeki] Unexpected Word Spacing in Brave

### ISSUE THREAD

**Issue by vhs-dev** [inblockio/DataAccounting#254]
Observed display issue on first launch of PKC wiki.

**Actual Result**
Words far apart making page difficult to read

**Expected Result**
Words are spaced for easy reading

**Screenshot**

![word-spacing-tweeki-issue](https://user-images.githubusercontent.com/97140109/148163545-32c208b9-f19c-494c-a1d0-fa26674044b2.png)

**Investigation**
Issue related to `font-family` selector applied to `body` combined with an emoji font declaration.

Causes issue:

```
-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,Liberation Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
```

Does not cause issue:

```
-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,Liberation Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol
```

Display issue can also be reproduced by introducing a syntax error into the selection rule (e.g. by preceding all fonts with a `,` for example).

GNU/Linux
Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by rht** [comment]
cc @thaider

**Comment by vhs-dev** [comment]
Just saw this issue on https://getbootstrap.com/docs/4.6/getting-started/introduction/. Closing.

**Comment by vhs-dev** [comment]
Looks like `font-family` comes from Bootstrap 4 as observed on https://getbootstrap.com/docs/4.6/getting-started/introduction/ website. In Tweeki we should look at overriding the Bootstrap default font stack if this bug persists.

**Comment by vhs-dev** [comment]
Recommended we shift to whatever Bootstrap 5 is using for default font stack as the issue cannot be observed here: https://getbootstrap.com/docs/5.0/getting-started/introduction/

For comparison bootstrap 5 and 4 into pages:

![bootstrap-5](https://user-images.githubusercontent.com/97140109/148183895-f6730e83-cce5-4b71-b6e9-8f2002eb9198.png)

![bootstrap-4](https://user-images.githubusercontent.com/97140109/148183934-e6849983-b42f-499a-a90f-2db185320786.png)

And the font stack for bs5:

```
system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"
```

**Comment by vhs-dev** [comment]
Confirmed PKC issue observed in OP resolved using Bootstrap 5 font stack, or simply by placing `system-ui,` at the beginning of the `font-family` style rule used on the `body`.

**Comment by vhs-dev** [comment]
Opened https://github.com/thaider/Tweeki/issues/227 which provides a better long-term solution, which is to upgrade to Bootstrap 5.

**Comment by FantasticoFox** [comment]
With this I think this is off our hands. Thanks @vhs-dev for the deep inspection.
