### ISSUE TITLE
[Tweeki] Watch button functionality throws an undescribed warning/error

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#255]
Click the Watch drop down from the Edit menu.
![image](https://user-images.githubusercontent.com/92349227/148170111-7cf449a0-bc8f-4bcc-b8ac-90187ab92151.png)

When you click the OK button, a warning image is displayed but no message. The OK button then becomes unresponsive.
![image](https://user-images.githubusercontent.com/92349227/148170129-3d26876d-4c21-4cab-83fb-84abf7a2e5c0.png)

**Comment by rht** [comment]
This could be the default MW behavior? cc @it-spiderman @pwirth.

**Comment by rht** [comment]
I observed it when the skin is Vector as well.

**Comment by FantasticoFox** [comment]
We removed the watch function.
