### ISSUE TITLE
[Tweeki] Reason values are not maintained on Protect Page

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#256]
Click Protect on Edit drop down
![image](https://user-images.githubusercontent.com/92349227/148172534-1d2b8ba2-4317-4500-9a6a-4130b0108bef.png)
Set custom values in the Edit box
![image](https://user-images.githubusercontent.com/92349227/148172567-b90717f6-65f1-43b2-b1e6-07f3ab66fb14.png)
Set up a reason and reason text on the protect page, then click Confirm
![image](https://user-images.githubusercontent.com/92349227/148172604-da667375-a43a-4627-92f9-d49c597a1bc7.png)
Click on Change protection back on the original page
![image](https://user-images.githubusercontent.com/92349227/148172624-4fc855fa-cee3-4e00-ace1-cc1e07c2260a.png)
The changes in the Edit section are still in place
![image](https://user-images.githubusercontent.com/92349227/148172654-6f48f4ab-28f4-4e18-a763-cbadf9f8d71c.png)
But the reason fields are not populated
![image](https://user-images.githubusercontent.com/92349227/148172686-0e67b8de-9d93-4c06-ad66-1f6e6b933cb6.png)

**Comment by FantasticoFox** [comment]
We deactivated the 'Protect' action as it seems not needed in our context.
