### ISSUE TITLE
Content Signature value is incorrect

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#257]
Click on Data Accounting Configurator
![image](https://user-images.githubusercontent.com/92349227/148174016-ed267efa-57a7-457f-bc2c-805453f809b7.png)
I’M a CHECKBOX under Content Signature looks wrong
![image](https://user-images.githubusercontent.com/92349227/148174043-1734a83f-e839-48d3-a83b-de50dc27bb3d.png)

**Comment by FantasticoFox** [comment]
Already fixed in 64d95400d2329038c7d92a63174060f1e07654d9
