### ISSUE TITLE
Incorrect "transclusion-hashes" text in footer links

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#261]
The text "transclusion-hashes" (doesn't make sense) appears as a footer for the links below...

Privacy policy
About Personal Knowledge Container
Disclaimers

<img width="378" alt="image" src="https://user-images.githubusercontent.com/92349227/148333107-995ef644-20c2-4a72-a00d-0394a90db08a.png">

**Comment by FantasticoFox** [comment]
Duplication of #243
