### ISSUE TITLE
Difference in Edit button (cosmetic only)

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#262]
Edit button looks different

<img width="866" alt="image" src="https://user-images.githubusercontent.com/92349227/148333404-32113435-53cb-47db-8392-a98c03ef557d.png">

Click on Privacy Policy at the bottom of the page

<img width="851" alt="image" src="https://user-images.githubusercontent.com/92349227/148333471-bcb7d723-be3f-4974-8d69-7a7f885f8990.png">

**Comment by FantasticoFox** [comment]
Show the current namespace context. We will not fix this.
