### ISSUE TITLE
Verification Hash link is broken

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#263]
On the Domain Snapshot Generator page if I click on the links in the Verification Hash column

<img width="626" alt="image" src="https://user-images.githubusercontent.com/92349227/148335237-c1b9b67f-f51f-422b-bf78-7c13eb45066f.png">

I'm getting - This site can’t be reached
<img width="666" alt="image" src="https://user-images.githubusercontent.com/92349227/148335264-6d0c0cc4-9b28-4280-ae8c-edea0566a619.png">

**Comment by FantasticoFox** [comment]
This is expected behavior. Unfortunately we don't let the user know. Will need to consult with @vhs-dev how we can make this user friendly.

**Comment by rht** [comment]
A super quick temp solution is to link it instead to e.g. `http://localhost:9352/rest.php/data_accounting/get_revision/<the hash>`

**Comment by FantasticoFox** [comment]
It now returns the verification data of a single revision, the one associated with the verification hash shown.

Fixed in 7a3b1b329dcfc201ca049636954201f3011162ac
