### ISSUE TITLE
Internal error when I import verified page to existing namespace

### ISSUE THREAD

**Issue by BennSim** [inblockio/DataAccounting#264]
Go to Import Verified Page screen. Check "Import to a namespace", select a namespace (any will cause the error), then click upload file

<img width="656" alt="image" src="https://user-images.githubusercontent.com/92349227/148337949-09ccf121-5953-4872-869f-38a881d70762.png">

Error page is displayed

<img width="840" alt="image" src="https://user-images.githubusercontent.com/92349227/148338189-16af76c7-ad1a-4870-a548-9a51fdee1232.png">

**Comment by pwirth** [comment]
is fixed here: https://github.com/inblockio/DataAccounting/pull/266
