### ISSUE TITLE
[Namespace Collision Resolution] Importer -> Achieve Feature Parity -> Move on Colission

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#269]
As we have a new importer the functionality to avoid namespace collision was lost. This needs to be recovered as it causes breaking problems in exchanging verified data between PKCs.

Related: https://github.com/inblockio/DataAccounting/issues/61

**Comment by FantasticoFox** [comment]
Please implement public function onImportHandlePageXMLTag (includes/hooks/:214)

**Comment by it-spiderman** [comment]
Done in https://github.com/inblockio/DataAccounting/commit/2d1d56bad0b08d613178778af3f6a7d74e8824d4

**Comment by FantasticoFox** [comment]
Fixed unexpected behavior: 7fc3adb7aab6264b6ccdebb3d13a52fff12c9148 
Do not run on every revision.

Expected behavior:
If the imported file has the same chain height as the file who exists in the domain -> do not import.
If the imported file has a longer chain height then the one present in the domain:
- move existing page to page_chainheight_x 
- import file with longer chain height to the now free title

Currently it seems to move the new incoming page into the namespace used for collision avoidance.  This is not expected behavior. @rht please help resolve.

**Comment by FantasticoFox** [comment]
There is unexpected behavior of the verifier:
When the page is moved, it has the same Genesis_Hash. When the API call comes in to retrieve all the verification data, it will receive it from the main branch and not from the side branch. Therefore the output of the external verifier is the one of the main branch and not of the side branch.

We need to implement proper fork logic to be able to manage all the different fork options.
