### ISSUE TITLE
Verification Hash Copy to Clipboard

### ISSUE THREAD

**Issue by vhs-dev** [inblockio/DataAccounting#273]
Currently we pop a new page for the Verification Hash links. Let's copy them to the clipboard instead.

- [x] Domain Manifest Generator
- [x] Domain Manifest Publisher
- [ ] Center Button on Generator

**Comment by FantasticoFox** [comment]
Generator is now linking to json content of that revision.
Domain manifest: verification hash is removed.
Center button on generator -> move to separate issue
