### ISSUE TITLE
Receive TIMESTAMP from standard API call with CONTENT instead of getting it from our own table

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#42]
timestamp should be sourced from the MediaWiki standard api alongside with the content text not from our database

**Comment by JeroenDeDauw** [comment]
You can use the [query API action](https://www.mediawiki.org/w/api.php?action=help&modules=query), more specifically with [the revisions property](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Brevisions).

**Comment by rht** [comment]
Ah, I think I remembered seeing that API, but had problem in getting the timestamp of just 1 revision. Now I have found the solution by specifying the `rvstartid` and `rvendid` to one particular revision, e.g. http://localhost:9352/api.php?action=query&prop=revisions&titles=Main%20Page&rvstartid=12&rvendid=12

**Comment by FantasticoFox** [comment]
We unify all calls to a single API to receive all data to verify the current revision. No extra-API calls will be employed.
