### ISSUE TITLE
Export is Limited (does not include all revisions)

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#43]
Export does seem to have a limitation on how many revisions to export. It seems not to include ALL revisions. This might lead to inconsistency in the data-structures and inability to verify the page.

**Comment by rht** [comment]
The relevant file to look at is at Mediawiki's source code includes/export/WikiExporter.php. Maybe BATCH_SIZE or maxRowCount.

**Comment by FantasticoFox** [comment]
can be solved by #116

**Comment by FantasticoFox** [comment]
Tested export and import of 673 revision. So this seems not to be a limitation. Close.
