### ISSUE TITLE
When importing a page originated from alice's domain, but with longer verified history, we currently don't verify if the old revisions are written+signed by alice

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#57]
A malicious counterparty could rewrite the history and use a different Metamask account to sign the revisions. And our current simplistic behavior is to blindly choose the page with longer verified history.

**Comment by FantasticoFox** [comment]
This should be a policy

**Comment by FantasticoFox** [comment]
This can be solved in using the guardian to verify on import and apply rules of a policy.

**Comment by FantasticoFox** [comment]
This logic needs to be incorporated for the policies which are enforced by the guardian.
